name: serializable_bloom_filter
description: Simple, efficient, and serializable implementation of bloom filters.
version: 1.0.1
repository: https://github.com/FlutterFlow/serializable_bloom_filter

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
